version: '3.1'
services:
  wallet:
    build: wallet
    image: wallet-image
    container_name: wallet
    ports:
      - "8080:8080"
    depends_on:
      - wallet-db
    environment:
      - SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://wallet-db:5432/wallet
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=iamroot
      - STATS_SERVER_URL=http://wallet:8080

  wallet-db:
    image: postgres:16-alpine
    container_name: postgres-wallet-db
    environment:
      - POSTGRES_PASSWORD=iamroot
      - POSTGRES_USER=postgres
      - POSTGRES_DB=wallet